### ISSUE TITLE
Text formatting

### ISSUE THREAD

**Issue by brennanfife** [Xairoo/nextjs-i18n-static-page-starter#2]
First off, thank you for creating this starter. Was using [next-translate](https://github.com/vinissimus/next-translate) until the last moment when I discovered Next 10's lack of support for export.
Is there any way one could also do text formatting, without resorting to css styling. There's the Trans component for React i18next. Couldn't find anything for pure i18next.

**Comment by xairoo** [comment]
Hey,

I use it like this (should work also without the tag* variables directly from your locales file:
```
<span
  className=""
  dangerouslySetInnerHTML={{
    __html: i18next.t(props.title, {
      tagSart: '<span class="">',
      tagEnd: '</span>',
    }),
  }}
/>
```

Or perhaps you'll try Format.JS. I have a starter for this too, but I haven't updated it like the current starter.
https://github.com/Xairoo/nextjs-i18n-formatjs-static-page-starter
You could just compare the code, only a few lines.

Good luck!

**Comment by brennanfife** [comment]
Awesome, that solution worked just as intended! TYSM!
